pub use crate::city::City;
pub use crate::state::State;

use serde::{Deserialize, Serialize};

// ($($c:tt: $s:tt => [$($nc:tt: [$($d:tt),*$(,)?]),*$(,)?] => [$($nsc:tt: [$($sd:tt),*$(,)?]),*$(,)?]),*$(,)?) => {
macro_rules! sub_cities {
    ($($c:tt: $s:tt),*$(,)?) => {
        paste::paste! {
            #[derive(Clone, Copy, Debug, Deserialize, Serialize, Eq, PartialEq, Hash)]
            #[allow(non_camel_case_types)]
            pub enum SubCity { $([<$c _ $s>]),* }
            impl SubCity {
                pub const fn sub_cities() -> &'static [Self] {
                    &[$(Self::[<$c _ $s>]),*]
                }

                pub const fn state(&self) -> State {
                    match self {
                        $(Self::[<$c _ $s>] => State::$s),*
                    }
                }
            }
        }
    }
}

// I think I should get rid of the railroad part of this..
sub_cities! {
    Concord: NH,
    Springfield: MA,
    Providence: RI,
    New_Haven: CT,
    Kingston: NY,
    Syracuse: NY,
    Rochester: NY,
    Erie: PA,
    Trenton: NJ,
    Pottstown: PA,
    Lancaster: PA,
    Bedford: PA,
    Uniontown: PA,
    Frederick: MD,
    Brantford: ON,
    London: ON,
    Youngstown: OH,
    Akron: OH,
    New_Philadelphia: OH,
    Fremont: OH,
    Findlay: OH,
    Chillicothe: OH,
    Winchester: OH,
    Maysville: OH,
    Perrysburg: OH,
    Dayton: OH,
    Shipshewana: IN,
    South_Bend: IN,
    Fort_Wayne: IN,
    Muncie: IN,
    Columbus: IN,
    Vincennes: IN,
    Terre_Haute: IN,
    Arcola: IL,
    Effingham: IL,
    West_Lafayette: IN,
    Cumberland: MD,
    Clarksburg: WV,
    Centralia: IL,
    Parkersburg: WV,
    Brideport: WV,
    Argos: IN,
    Ligonier: IN,
    Kenosha: WI,
    Madison: WI,
    Green_Bay: WI,
    Eau_Claire: WI,
    Wisconsin_Dells: WI,
    La_Crosse: WI,
    Gold_Run: CA,
    Herlong: CA,
    Santa_Rosa: CA,
    San_Jose: CA,
    Santa_Barbara: CA,
    Santa_Maria: CA,
    San_Simeon: CA,
    Big_Sur: CA,
    Lancaster: CA,
    Bakersfield: CA,
    Modesto: CA,
    Amboy: CA,
    Sulphur: OK,
    Lovelock: NV,
    Beowawe: NV,
    Indio: CA,
    Blythe: CA,
    Fresno: CA,
    Tulare: CA,
    Helper: UT,
    Green_River: UT,
    Fruita: CO,
    Nephi: UT,
    Fillmore: UT,
    San_Bernardino: CA,
    Chester: CA,
    Paradise: CA,
    Brawley: CA,
    Yuma: AZ,
    Aztec: NM,
    Crescent_City: CA,
    Fortuna: CA,
    Mesquite: NV,
    Enoch: UT,
    Deming: NM,
    Mariana: AZ,
    Lordsburg: NM,
    Pomerene: AZ,
    Wickenburg: AZ,
    Marfa: TX,
    Sierra_Blanca: TX,
    Toyah: TX,
    Santa_Rosa: NM,
    Albuquerque: NM,
    Socorro: NM,
    Arrey: NM,
    Ancho: NM,
    Alamogordo: NM,
    Grants: NM,
    Church_Rock: NM,
    Sedona: AZ,
    Taylor: AZ,
    Springer: NM,
    Watrous: NM,
    Clovis: NM,
    Salem: OR,
    Eugene: OR,
    Grants_Pass: OR,
    Roseburg: OR,
    Twin_Falls: ID,
    Biggs_Junction: OR,
    Pendleton: OR,
    Mountain_Home: ID,
    Boise: ID,
    Baker_City: OR,
    Huntington: OR,
    Shelby: MT,
    Wilbur: WA,
    Olympia: WA,
    Wapato: WA,
    Bristol: WA,
    Ritzville: WA,
    Colfax: WA,
    Klamath_Falls: OR,
    Chemult: OR,
    Seven_Mile: WA,
    Shaniko: OR,
    Dillon: MT,
    Monida: MT,
    Missoula: MT,
    Noxon: MT,
    Thompson_Falls: MT,
    St_Regis: MT,
    Cataldo: ID,
    Custer: SD,
    Cheyenne: WY,
    Hardin: MT,
    Sheridan: WY,
    Kaycee: WY,
    Big_Timber: MT,
    Bozeman: MT,
    Townsend: MT,
    Provo: UT,
    Declo: ID,
    Harlem: MT,
    Havre: MT,
    Sandpoint: ID,
    Whitefish: MT,
    Chester: MT,
    Culbertson: MT,
    Wolf_Point: MT,
    Glasgow: MT,
    Malta: MT,
    Marblemount: WA,
    Idaho_Falls: ID,
    Ogden: UT,
    Malad_City: ID,
    Montpelier: ID,
    Neihart: MT,
    Geraldine: MT,
    Forsyth: MT,
    Roundup: MT,
    Harlowton: MT,
    West_Wendover: NV,
    Baker: MT,
    Laramie: WY,
    Elk_Mountain: WY,
    Creston: MT,
    Evanston: WY,
    Little_America: WY,
    Point_Of_Rocks: WY,
    Bloomfield: MT,
    Terry: MT,
    Wibaux: MT,
}
